### ISSUE TITLE
Change parameters of the model

### ISSUE THREAD

**Issue by skycolt** [alanderos91/BioSimulator.jl#19]
Hello,

I am trying to change parameters in the model but can't even find the place they are stored, neither can I find a function for that. Could you help me with this?

Thanks
Wenzhe

**Comment by alanderos91** [comment]
Currently it is not possible to change parameters *during* a simulation. You can change parameters by "redefining" a reaction:

```julia
model <= Reaction("name_of_reaction", new_parameter, "formula")
```

**Comment by skycolt** [comment]
Thank you for this! And is there a way to check the value of the parameters in the model?

Wenzhe

**Comment by skycolt** [comment]
BTW. Is there a function that I can read the simulation result into variables for future analysis?

Thanks

**Comment by alanderos91** [comment]
1. The `Network` type has this information. For example,
```julia
model.reaction_list[:birth].rate
```
This retrieves the parameter for a reaction channel called "birth".

2. You can extract the results in two ways:
```julia
result = simulate(...)

# directly
id2index = result.id2index
simulation_data = result.simulation_data
ntrials = length(simulation_data)

protein = [simulation_data[n][k][id2index[:protein]] for n in 1:ntrials, k in 1:length(simulation_data[n])]

# with DataFrames
using DataFrames

DataFrame(result)
```

Here `simulation_data` stores the trajectory for each realization of the process, so that `simulation_data[n]` is the `n`-th sample path. The index `k` steps through each *recorded* event. The [DataFrames](https://juliadata.github.io/DataFrames.jl/stable/) approach is more straightforward, and will let you save results if you read their documentation.

**Comment by skycolt** [comment]
Thank you very much!
