### ISSUE TITLE
Question about how to get time course for specific variables

### ISSUE THREAD

**Issue by skycolt** [alanderos91/BioSimulator.jl#30]
It's not a question. I just didn't figure out a way to quickly get the time course for certain variable. I'm used to the 2D matrix storage format of variable values, you can simply write M(:,x) to get the time couse or M(x,:) to get a specific time point. The current data is stored as an array of arrays, I didn't figure out a way as simple to get time course yet. Please inform me if there is a simple way.

Thanks!
Wenzhe

**Comment by alanderos91** [comment]
Take a look here:
https://alanderos91.github.io/BioSimulator.jl/dev/man/tutorials/

For a single realization:

```julia
trajectory[[3,4], :]
```

will select the entire history for the 3rd and 4th components. If you have
multiple realizations (an ensemble):

```julia
ensemble[3][[3,4], :]
```

selects the same data for the third realization.

The interface will probably change again because this is a bit clunky. Feel
free to make suggestions for syntax.

**Comment by skycolt** [comment]
Thanks! I missed that part of the tutorial. 

I feel like how the current data is arranged. I'll let you know if something jumps into my mind
